version: '3.8'

services:
  backend:
    build: './backend'
    ports:
    
      - "5000:5000"
    environment:
    
      - MONGO_URI=mongodb+srv://subacc2426_db_user:A0BUe767enxs7uZq@cluster0.n06ff2m.mongodb.net/Devops?appName=Cluster0
    
  frontend:
    build: './frontend'
    ports:

      - "5173:3000"
    depends_on:
      - backend
