version: '3.8'

services:
  backend:
    build: './backend'
    ports:
      # Host Port 5000 -> Container Port 5000 (To match the app's log: "Server running on port 5000")
      - "5000:5000"
    environment:
      # Ensure your MONGO_URI is wrapped in quotes if it contains special characters
      - MONGO_URI=mongodb+srv://subacc2426_db_user:A0BUe767enxs7uZq@cluster0.n06ff2m.mongodb.net/Devops?appName=Cluster0
    
  frontend:
    build: './frontend'
    ports:
      # Host Port 3000 -> Container Port 80 (The standard port for the Nginx web server)
      - "5173:5173"
    depends_on:
      - backend
    # Note: env_file is generally not needed for a built static frontend